blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import ArticleListView, ArticleDetailView, ArticleCreateView, ArticleUpdateView, ArticleDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', ArticleListView.as_view(), name='list'),
    path('article/<int:pk>/', ArticleDetailView.as_view(), name='article'),
    path('create/', ArticleCreateView.as_view(), name='create_article'),
    path('update/<int:pk>/', ArticleUpdateView.as_view(), name='update_article'),
    path('delete/<int:pk>/', ArticleDeleteView.as_view(), name='delete_article'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

NULLABLE = {'null': True, 'blank': True}


class Article(models.Model):
    title = models.CharField(max_length=250, verbose_name='Заголовок')
    slug = models.CharField(max_length=250, verbose_name='slug', **NULLABLE)
    body = models.TextField(verbose_name='Содержимое')
    preview = models.ImageField(upload_to='blog/', **NULLABLE, verbose_name='Изображение')
    creation_date = models.DateTimeField(auto_now_add=True, verbose_name='дата создания')
    is_published = models.BooleanField(default=True, verbose_name='опубликовано')
    view_counts = models.IntegerField(default=0, verbose_name='просмотры')

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'статья'
        verbose_name_plural = 'статьи'

blog/forms.py
from django import forms

from blog.models import Article
from catalog.models import Product


class StyleFormMixin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ArticleForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Article
        fields = ('title', 'body', 'preview',)

blog/views.py
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from pytils.translit import slugify

from blog.forms import ArticleForm
from blog.models import Article


class ArticleListView(ListView):
    model = Article
    extra_context = {'title': 'Блог'}

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class ArticleDetailView(DetailView):
    model = Article
    extra_context = {'title': 'Статья'}

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.view_counts += 1
        self.object.save()
        return self.object


class ArticleCreateView(CreateView):
    model = Article
    form_class = ArticleForm
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        new_art = form.save()
        new_art.slug = slugify(new_art.title)
        new_art.save()
        return super().form_valid(form)


class ArticleUpdateView(UpdateView):
    model = Article
    form_class = ArticleForm

    def get_success_url(self):
        return reverse('blog:article', args=[self.object.pk])


class ArticleDeleteView(DeleteView):
    model = Article
    success_url = reverse_lazy('blog:list')

blog/templates/blog/article_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="col-12">
    <div class="row text-left">
        <div class="col-6">
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <h6>{{object.title}} </h6>
                    <p>{{object.body}} </p>
                    <button type="submit" class="btn btn-success" >Удалить статью</button>
                </form>
            </div>
        </div>
    </div>
</div>


{%endblock%}

blog/templates/blog/article_detail.html
{% extends 'catalog/base.html' %}

{% block content %}
{% load custom_tags %}

<div class="row text-left">
    <div class="card mb-3" style="max-width: 740px;">
      <div class="row g-0">
        <div class="col-md-4">
          <img src="{{ object.preview|mediapath }}" height="200" />
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h6 class="card-title" >{{object.title}}</h6>
            <p class="card-text">{{object.body}}</p>
            <h6 class="card-text">Количество просмотров: {{object.view_counts}}</h6>
            <p class="card-text">Дата создания: {{object.creation_date}}</p>
          </div>
        </div>
      </div>
    </div>
</div>

{%endblock%}

blog/templates/blog/article_form.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="col-12">
    <div class="row text-right">
        <div class="col-6">
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form.as_p}}
                    <button type="submit" class="btn btn-success" >
                    {% if object%}
                        Сохранить изменения
                    {% else%}
                        Создать статью
                    {% endif%}</button>
                </form>
            </div>
        </div>
    </div>
</div>


{%endblock%}

blog/templates/blog/article_list.html
{% extends 'catalog/base.html' %}

{% block content %}
{% load custom_tags %}
<div class="row text-center  mb-3">
    <a type="button" class="btn btn-warning" href="{% url 'blog:create_article' %}">Написать статью</a>
</div>
<div class="row text-center">
    {% for object in object_list%}
    <div class="card mb-3" style="max-width: 540px;">
      <div class="row g-0">
        <div class="col-md-4">
          <img src="{{ object.preview|mediapath }}"  height="200" />
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h6 class="card-title" >{{ object.title }}</h6>
            <p class="card-text">{{ object.body|slice:"80"}}...</p>
              <a type="button" class="btn btn-success" href="{% url 'blog:article' object.pk%}">Читать</a>
              <a type="button" class="btn btn-outline-secondary" href="{% url 'blog:update_article' object.pk%}">Edit</a>
              <a type="button" class="btn btn-outline-danger" href="{% url 'blog:delete_article' object.pk%}">Delete</a>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
</div>
{%endblock%}