blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import ArticleListView, ArticleDetailView, ArticleCreateView, ArticleUpdateView, ArticleDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', ArticleListView.as_view(), name='list'),
    path('article/<int:pk>/', ArticleDetailView.as_view(), name='article'),
    path('create/', ArticleCreateView.as_view(), name='create_article'),
    path('update/<int:pk>/', ArticleUpdateView.as_view(), name='update_article'),
    path('delete/<int:pk>/', ArticleDeleteView.as_view(), name='delete_article'),
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.apps import CatalogConfig
from catalog.views import contacts, ProductListView, ProductDetailView, ProductCreateView, ProductUpdateView, \
    ProductDeleteView, VersionCreateView, categories

app_name = CatalogConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='home'),
    path('contacts/', contacts, name='contacts'),
    path('product/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='product'),
    path('create/', ProductCreateView.as_view(), name='create_product'),
    path('update/<int:pk>/', ProductUpdateView.as_view(), name='update_product'),
    path('delete/<int:pk>/', ProductDeleteView.as_view(), name='delete_product'),
    path('create_version/', VersionCreateView.as_view(), name='create_version'),
    path('categories/', categories, name='categories'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models

from users.models import User

NULLABLE = {'null': True, 'blank': True}


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='наименование')
    description = models.TextField(verbose_name='описание')
    preview = models.ImageField(upload_to='products/', verbose_name='изображение', **NULLABLE)
    category = models.ForeignKey('Category', on_delete=models.CASCADE, verbose_name='категория')
    price = models.IntegerField(verbose_name='цена за покупку')
    creation_date = models.DateTimeField(auto_now=False, auto_now_add=True, verbose_name='дата создания')
    modified_date = models.DateTimeField(auto_now=True, auto_now_add=False, verbose_name='дата последнего изменения')
    product_owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Владелец', **NULLABLE)

    def __str__(self):
        return f'{self.name} {self.description}'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        ordering = ('name',)


class Category(models.Model):
    name = models.CharField(max_length=150, verbose_name='наименование')
    description = models.TextField(max_length=150, verbose_name='описание')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'
        ordering = ('name',)


class Version(models.Model):
    product = models.ForeignKey('Product', on_delete=models.CASCADE, verbose_name='продукт')
    version = models.IntegerField(verbose_name='номер версии')
    version_name = models.CharField(max_length=100, verbose_name='название версии')
    is_current = models.BooleanField(default=True, verbose_name='активная версия')

    def __str__(self):
        return f'{self.version} {self.version_name}'

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'
        ordering = ('version',)

catalog/forms.py
from django import forms

from catalog.models import Product, Version


class StyleFormMixin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Product
        exclude = ('creation_date', 'modified_date', 'product_owner')

    def clean_name(self):
        cleaned_data = self.cleaned_data.get('name',)
        elimination_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']
        for item in elimination_words:
            if item.lower() in cleaned_data.lower():
                raise forms.ValidationError('Запрещенное слово')
        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data.get('description',)
        elimination_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']
        for item in elimination_words:
            if item.lower() in cleaned_data.lower():
                raise forms.ValidationError('Запрещенное слово')
        return cleaned_data


class VersionForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Version
        fields = '__all__'

catalog/views.py
from django.db import transaction
from django.forms import inlineformset_factory
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView

from catalog.forms import ProductForm, VersionForm
from catalog.models import Product, Version
from catalog.services import get_categories_from_cache


class ProductListView(ListView):
    model = Product
    template_name = 'catalog/home.html'
    extra_context = {'title': 'Главная'}


def contacts(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f'You have new message from {name}({phone}): {message}')
    context = {
        'title': 'Контакты'
    }
    return render(request, 'catalog/contacts.html', context)


class ProductDetailView(DetailView):
    model = Product
    extra_context = {'title': 'Продукт'}


class ProductCreateView(CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:home')

    def form_valid(self, form: ProductForm):
        product = form.save()
        product.product_owner = self.request.user
        product.save()
        return super().form_valid(form)


class ProductUpdateView(UpdateView):
    model = Product
    form_class = ProductForm

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormSet = inlineformset_factory(self.model, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            formset = VersionFormSet(self.request.POST, instance=self.object)
        else:
            formset = VersionFormSet(instance=self.object)
        context_data['formset'] = formset
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        with transaction.atomic():
            if form.is_valid():
                self.object = form.save()
                if formset.is_valid():
                    formset.instance = self.object
                    formset.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('catalog:product', args=[self.object.pk])


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:home')


class VersionCreateView(CreateView):
    model = Version
    form_class = VersionForm
    success_url = reverse_lazy('catalog:home')
    template_name = 'users/register.html'


def categories(request):
    context = {
        'object_list': get_categories_from_cache(),
        'title': 'Категории',
    }
    return render(request, 'catalog/categories.html', context)

catalog/templates/catalog/base.html
<!doctype html>
{% load static %}
{% load custom_tags %}
<html lang="ru" data-bs-theme="auto">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{title}}</title>
    <!-- Bootstrap core CSS -->
    <link href="{%static 'css/bootstrap.min.css'%}" rel="stylesheet" />
</head>
<body>

<div class="pricing-header bg-light px-3 py-3 pt-md-3 pb-md-3 mx-auto text-center">
    <h1 class="display-4"> Skystore</h1>
    <p class="lead">Skystore - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели
        продать</p>
</div>

{% include 'catalog/includes/inc_main_menu.html' %}

<div class="container">
    {%block content%}
    {%endblock%}
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                <img src="{%static 'images/pin.png'%}" alt="pin" width="200">
                <br>
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h6>Категории</h6>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h6>Дополнительно</h6>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="{% url 'blog:list' %}">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h6>О нас</h6>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

</body>
</html>

catalog/templates/catalog/categories.html
{% extends 'catalog/base.html' %}

{% block content %}
{% load custom_tags %}
<div class="row text-center">
    {% for object in object_list%}
    <div class="card mb-3" style="max-width: 540px;">
      <div class="row g-0">
        <div class="col-md-8">
          <div class="card-body">
            <h6 class="card-title" >{{ object.name }}</h6>
          </div>
            <div class="card-body">
            <h7 class="card-title" >{{ object.description }}</h7>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
</div>
{%endblock%}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="row text-start">
    <div class="col-lg-9 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <table class="table table-striped">
                    <tr>
                        <td class="w-25">Страна</td>
                        <td>USA</td>
                    </tr>
                    <tr>
                        <td class="w-25">ИНН</td>
                        <td>91-1144442</td>
                    </tr>
                    <tr>
                        <td class="w-25">Адрес</td>
                        <td>Redmond,WA,98052-6399</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <div class="col-lg-3 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h5 class="my-0 font-weight-normal">Свяжитесь с нами</h5>
            </div>
            <div class="card-body">
                <form method="post" action="" class="form-floating">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="name">Имя</label>
                        <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                    </div>
                    <div class="mb-3">
                        <label for="phone">Телефон</label>
                        <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                    </div>
                    <div class="mb-3">
                        <label for="message">Сообщение</label>
                        <textarea type="text" name="message" class="form-control" id="message" placeholder="Сообщение" required></textarea>
                    </div>
                    <button type="submit" class="btn btn-lg btn-block btn-outline-secondary">Отправить</button>
                </form>

            </div>
        </div>
    </div>
</div>
{%endblock%}

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}

{% block content %}
{% load custom_tags %}
<div class="row text-center  mb-3">{% if user.is_authenticated %}
    <a type="button" class="btn btn-success" href="{% url 'catalog:create_product' %}">Создать продукт</a>
</div>
<div class="row text-center  mb-3">
    <a type="button" class="btn btn-success" href="{% url 'catalog:create_version' %}">Добавить версию</a>
</div>{% endif %}
<div class="row text-center">
    {% for object in object_list%}
    <div class="card mb-3" style="max-width: 540px;">
      <div class="row g-0">
        <div class="col-md-4">
          <img src="{{ object.preview|mediapath }}"  height="200" />
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h6 class="card-title" >{{ object.name }}</h6>
            <p class="card-text">{{ object.description|slice:"100"}}...</p>
              <a type="button" class="btn btn-outline-success" href="/product/{{ object.pk }}/">$ {{ object.price}}</a>
              {% if user.is_authenticated %}
              <a type="button" class="btn btn-outline-secondary" href="{% url 'catalog:update_product' object.pk%}">
                  Edit
                  </a>
              <a type="button" class="btn btn-outline-danger" href="{% url 'catalog:delete_product' object.pk%}">
                  Delete
                  </a>{% endif %}
                  <div class="text">
                      {% if not object.version_set.all %}
                        <p>Нет активных версий</p>
                      {% endif %}
                    {% for version in object.version_set.all %}
                        {% if version.is_current %}
                            <p>Активная версия: {{ version.version_name }}</p>
                        {% endif %}
                    {% endfor %}
                  </div>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
</div>
{%endblock%}

catalog/templates/catalog/product.html
{% extends 'catalog/base.html' %}

{% block content %}
{% load custom_tags %}

<div class="row text-left">
    <div class="card mb-3" style="max-width: 740px;">
      <div class="row g-0">
        <div class="col-md-4">
          <img src="{{ object.preview|mediapath }}" height="200" />
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h6 class="card-title" >{{object.name}}</h6>
            <p class="card-text">{{object.description}}</p>
            <p class="card-text">Категория: {{object.category}}</p>
            <p class="card-text">Цена: ${{object.price}}</p>
            <p class="card-text">Дата создания: {{object.creation_date}}</p>
            <p class="card-text">Дата последнего изменения: {{object.modified_date}}</p>
          </div>
        </div>
      </div>
    </div>
</div>

{%endblock%}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="col-12">
    <div class="row text-left">
        <div class="col-6">
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <h6>{{object.name}} </h6>
                    <p>{{object.description}} </p>
                    <button type="submit" class="btn btn-success" >Удалить продукт</button>
                </form>
            </div>
        </div>
    </div>
</div>


{%endblock%}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}

{% block content %}
{% load custom_tags %}

<div class="row text-left">
    <div class="card mb-3" style="max-width: 740px;">
      <div class="row g-0">
        <div class="col-md-4">
          <img src="{{ object.preview|mediapath }}" height="200" />
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h6 class="card-title" >{{object.name}}</h6>
            <p class="card-text">{{object.description}}</p>
            <p class="card-text">Категория: {{object.category}}</p>
            <p class="card-text">Цена: ${{object.price}}</p>
            <p class="card-text">Дата создания: {{object.creation_date}}</p>
            <p class="card-text">Дата последнего изменения: {{object.modified_date}}</p>
          </div>
        </div>
      </div>
    </div>
</div>

{%endblock%}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="col-12">
    <div class="row-12">
        <form method="post" enctype="multipart/form-data" class="row">
            <div class="col-6">
                <div class="card-body">
                        {% csrf_token %}
                        {{form.as_p}}
                        <button type="submit" class="btn btn-success" >
                        {% if object%}
                            Сохранить изменения
                        {% else%}
                            Создать продукт
                        {% endif%}</button>
                </div>
            </div>
            <div class="col-6">
                <div class="card">
                    <div class="card-header">Версии</div>
                    <div class="card-body">
                        {{ formset.management_form }}
                        {% for form in formset.forms %}
                            {{form.as_p}}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>


{%endblock%}

catalog/templates/catalog/version_form.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="col-12">
    <div class="row text-right">
        <div class="col-6">
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form.as_p}}
                    <button type="submit" class="btn btn-success" >
                        Создать версию
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>


{%endblock%}